# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Ngoding"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://ngodingdewa.github.io"
tags = []
features = []
min_version = "0.41"
baseurl = "/" 
paginate = 6
disqusShortname = "ngodingdewa"
copyright = "Copyright {year} ngodingdewa. All rights reserved."

[author]
  name = "ngodingdewa"
  avatar = "https://semantic-ui.com/images/avatar2/small/elyse.png"
  description = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""

[params]
  logo = "ngodingdewa-logo.png"
  logofixed = "avatar.png"
  title = "Ngoding Dewa - Free development tutorial - Laravel, git, javascript"
  subtitle = "Free development tutorial - Laravel, git, javascript."
  description = "Free front-end and back-end tutorial, web development tutorials on JavaScript, git and more."
  metaDescription = "Free front-end and back-end tutorial, web development tutorials on JavaScript, git and more."
  googleAnalytics = ""
  twitterName = "ngodingdewa"
  fbName = "ngodingdewa"
  githubName = "ngodingdewa"

[permalinks]
  post = "/post/:slug/"


# Menu main
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 100

[[menu.main]]
  name = "Laravel"
  url = "/categories/Laravel/"
  weight = 99

[[menu.main]]
  name = "React.js"
  url = "/categories/react/"
  weight = 98

[[menu.main]]
  name = "Vue.js"
  url = "/categories/react/"
  weight = 97

[[menu.main]]
  name = "Angular"
  url = "/categories/angular/"
  weight = 96

[[menu.main]]
  name = "Git"
  url = "/categories/git/"
  weight = 95

[[menu.main]]
  name = "Codeigniter"
  url = "/categories/codeigniter/"
  weight = 94
